### ISSUE TITLE
cannot free memory after creating a large number of bitmaps

### ISSUE THREAD

**Issue by ayman-eltemsahi** [RoaringBitmap/CRoaring#222]
Hi,

In my application, I need to create a large number of bitmaps that can reach 10^8 bitmaps. But when I free the memory for all these bitmaps, something doesn't work cause linux still reports that the process is using about 7 GB of memory which is pretty much the same as before free.

I created this test app which creates many bitmaps, adds one number to each and then frees the memory. At the end of program, the process is still holding 7 GB of memory.

```c
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "roaring.h"

#define TEST_SIZE 50000000 // 50 * 10^6

int main()
{
    printf("Will create %d bitmaps\n", TEST_SIZE);
    roaring_bitmap_t **bitmaps = calloc(TEST_SIZE, sizeof(roaring_bitmap_t *));
    for (uint32_t i = 0; i < TEST_SIZE; ++i)
    {
        bitmaps[i] = roaring_bitmap_create();
        roaring_bitmap_add(bitmaps[i], i);
    }

    printf("Created %d bitmaps\n", TEST_SIZE);
    getchar();

    printf("Will free %d bitmaps\n", TEST_SIZE);
    for (uint32_t i = 0; i < TEST_SIZE; ++i)
    {
        roaring_bitmap_free(bitmaps[i]);
    }
    free(bitmaps);
    printf("Freed %d bitmaps\n", TEST_SIZE);

    // at this point, the used memory is 7,038,072 KB
    getchar();
    return 0;
}
```

Am I missing anything while creating or freeing?

**Comment by lemire** [comment]
How much virtual memory the process receives is not up to the library. We call malloc and free. It is entirely up to the standard library and operating system to decide when to reclaim real and virtual memory.

We have tools like valgrind and address sanitizers to look for memory leaks. As far as we know, there is no memory leak in CRoaring. If you think that there is, describe a test that exposes a memory leak. E.g., run your program through valgrind (or a similar tool), or compile it with memory sanitizers.

Closing. Please reopen if you identify a memory leak.

**Comment by nkurz** [comment]
> Am I missing anything while creating or freeing?

Extending on Daniel's answer, the issue is that "free" in Linux almost
never returns memory to the system.   Instead, it only marks the
memory as available for internal reuse by the same process.  Which is
to say, you are doing everything right, but your expectations are
wrong.   If you could arrange to free the bitmaps within your loop
rather than at the end, you could reduce the "high water mark" of
maximum memory used.   Otherwise things are working as expected.

On the bright side, this is usually a smaller issue than it seems.
Memory is regularly "overcommitted" in Linux, and the most likely
outcome is that you'll use a little extra swap space with minimal
performance degradation.  In the case that the extra memory usage is a
real world problem, your solution probably involves using a custom
memory allocator of some form.   This Stackoverflow question has some
answers that might give useful hints:
https://stackoverflow.com/questions/2215259/will-malloc-implementations-return-free-ed-memory-back-to-the-system.

--nate

**Comment by lemire** [comment]
@nkurz The stack overflow link is brilliant.

**Comment by ayman-eltemsahi** [comment]
@nkurz thanks for that link, it does show the problem. I could generate the same behavior with just `malloc`.
