### ISSUE TITLE
rank and select function has different counting behaviour.

### ISSUE THREAD

**Issue by hurricane1026** [RoaringBitmap/CRoaring#223]
rank(first_element) return 1;
select(1, &first_element), then first_element get the second element.

I think the 2 functions should be inverse-function for each other.
I wonder that was by design or a bug?

**Comment by lemire** [comment]
Let us see how it is documented...

```
/**
* roaring_bitmap_rank returns the number of integers that are smaller or equal
* to x.
*/
uint64_t roaring_bitmap_rank
```

So `rank(first_element) return 1`... seems correct... as per the comment.


It also matches how things are defined in statistics... quoting wikipedia...

"For example, the numerical data 3.4, 5.1, 2.6, 7.3 are observed, the ranks of these data items would be 2, 3, 1 and 4 respectively."

But it is problematic because in computing, the element at index 0 is the first one and so forth. There may not be a good resolution to this age-old problem.

Then...

```
/**
 * If the size of the roaring bitmap is strictly greater than rank, then this
   function returns true and set element to the element of given rank.
   Otherwise, it returns false.
 */
bool roaring_bitmap_select
```

I will right away improve the documentation.

> I think the 2 functions should be inverse-function for each other.

This was not specified but I admit that as things stand, this could be misleading. There is an off-by-one issue.


> I wonder that was by design or a bug?

I don't think it is a bug per se but there is a documentation issue.

**Comment by lemire** [comment]
I have just checked in new code which documents this issue more properly. You have to do +1 or -1 if you want to get one to be the inverse of the other. 

Thanks for reporting this issue.

**Comment by lemire** [comment]
Oh. I remember now why it is like so. 

If you do "rank" and it is a value smaller than the smallest value, you want to get 0.

**Comment by hurricane1026** [comment]
maybe select(1, *ptr) can get the rank1 element? I don‘t think select(0,*ptr) was a elegant design.

**Comment by lemire** [comment]
@hurricane1026 

In C/C++, we do select the first element with zero (`array[0]` is the first element). It is not true in all programming languages, but certainly true in C/C++.

In any case, we cannot change the behavior of the public API as it would break existing code. Though the documentation could have been clearer (it is clearer now), it was unambiguously documented.

**Comment by lemire** [comment]
As for why we select starting at zero, please see 

Edsger W. Dijkstra. Why Numbering Should Start at Zero, 1982.

and

Cassani and Conway, Neumbering, 2017.
