### ISSUE TITLE
Get memory usage of roaring_bitmap_t

### ISSUE THREAD

**Issue by decster** [RoaringBitmap/CRoaring#287]
For our use case, bitmaps are maintained in a cache, so we need to track the memory usage of each roaring_bitmaps, an API to get memory usage would be great.

**Comment by Ezibenroc** [comment]
Have you seen [`roaring_bitmap_statistics`](https://github.com/RoaringBitmap/CRoaring/blob/cb3816f7189c690b56afe0f11a8a50ce2d617fa7/include/roaring/roaring.h#L669-L673)? This does not return the full memory footprint of the whole bitmap, but at least the containers.

**Comment by decster** [comment]
The extra overhead of roaring_bitmap_statistics seems too high, e.g. iterate all elements to get min/max

**Comment by lemire** [comment]
@decster If you call `roaring_bitmap_shrink_to_fit`and then `roaring_bitmap_portable_size_in_bytes`, you should get a good measure of the size of the data structure.

If this is not what you are looking for, consider producing a pull request.

**Comment by lemire** [comment]
Note that because the data structure is dynamic and rely on heap allocation, there is no precise definition of memory usage. The heap usage is allocated in terms of virtual memory that gets translated into physical pages being allocated.

How much memory do I use when I do the following...


```
char * x = malloc(100000);
```

The answer, on many systems, is zero. This might very well be a purely virtual allocation (no RAM gets allocated).

Meanwhile what is the memory usage of...

```
char * x = malloc(1);
x[0] = 1;
```

On some systems where you have 2 MB pages, that could be 2 MB.

So it is a complex issue that is very much system dependent.

What the library can know is how much memory the serialized data structure takes. That it can report.

We don't want to track the allocation of physical pages inside the library. That is outside of our scope.

**Comment by lemire** [comment]
... and even calling `roaring_bitmap_portable_size_in_bytes` or `roaring_bitmap_size_in_bytes` is not going to be constant time. It is cheap, but you do not want to do it constantly.

**Comment by decster** [comment]
Regarding precise memory usage stats, yes it is impractical,  we just want to get the size stats of all the malloced memory, although it's not precise it's good enough.

Another thought, in our use case bitmaps are immutable/copy-on-write, so in theory, all read/iterate methods can operate directly on a binary buffer/string without deserialization.

**Comment by lemire** [comment]
@decster The functions I suggest will give you a pretty good estimate of the total malloc.

> Another thought, in our use case bitmaps are immutable/copy-on-write, so in theory, all read/iterate methods can operate directly on a binary buffer/string without deserialization.

We support that already. Look for 'frozen' in the API. At the current time, this requires a different serialization (to simplify memory accesses under alignment constraints).

I am going to close this. Reopen a new issue if you have remaining concerns.
