### ISSUE TITLE
When should we use lazy_or and when should we just use the normal or?

### ISSUE THREAD

**Issue by CharlesChen888** [RoaringBitmap/CRoaring#453]
I notice that when total cardinality reaches `ARRAY_LAZY_LOWERBOUND` (1024), lazy union tends to convert array into bitset:
```
int totalCardinality = src_1->cardinality + src_2->cardinality;
if (totalCardinality <= ARRAY_LAZY_LOWERBOUND) {
       // normal union
       return;
}
// lazy union (create a new bitset as result)
```
Does this mean when using `roaring_bitmap_or_many_heap` or `roaring_bitmap_or_many`, we always assume that in the final result, containers will be bitsets?

I haven't done any benchmark, but perhaps someone has done it already: if we knew the result container would be a bitset (card > 4096), is lazy union (create a bitset and perform setting bits for every src container) faster than vectorized array union (do SSE array union for all src arrays and only perform setting bits for the result array)?

And the same questions are also raised when I read the code of XOR.

**Comment by lemire** [comment]
> we always assume that in the final result, containers will be bitsets?

We do not make this assumption. We simply assume that operations will be faster and that the eventual cost of converting the bitsets back (when needed) will be cheap. This is generally the case in our benchmarks.

It is cheap to compute a union between an array and a bitset. Even the union between two bitsets is cheap, certainly cheaper than computing the union between two arrays made of thousands of values. So it is advantageous to favour bitset containers during the computation.

> perhaps someone has done it already

We have, yes. Of course, this is always subject to tuning since this code is based on heuristics.

**Comment by lemire** [comment]
I have added comments directly in the code.
